kind: Deployment
apiVersion: apps/v1
metadata:
  name: crm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: crm
    spec:
      containers:
        - name: crm
          image: 'registry.ocp4.pacosta.com:8443/crm/crm:1.98'
          ports:
            - containerPort: 9797
              protocol: TCP
          env:
            - name: spring.cloud.consul.host
              value: consul-service.test.svc.cluster.local
            - name: spring.config.import
              value: 'consul:consul-service.test.svc.cluster.local:8500'
            - name: spring.data.mongodb.newdb2.uri
              value: 'mongodb://mongodb.test.svc.cluster.local:27017/Eoffice'
            - name: spring.data.mongodb.newdb1.uri
              value: 'mongodb://mongodb.test.svc.cluster.local:27017/Eoffice'
            - name: spring.kafka.producer.bootstrap-servers
              value: '172.30.205.91:9092'
            - name: spring.kafka.consumer.bootstrap-servers
              value: '172.30.205.91:9092'
            - name: spring.security.oauth2.resourceserver.jwt.jwk-set-uri
              value: >-
                http://keycloak1-test.apps.ocp4.pacosta.com/realms/master/protocol/openid-connect/certs
            - name: minio.bucket.name
              value: crm
            - name: minio.url
              value: 'http://172.30.218.2:9000'
            - name: minio.rest-url
              value: 'http://172.30.218.2'
            - name: minio.rest-port
              value: '9000'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: worker6.ocp4.pacosta.com
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
status:
  observedGeneration: 20
  replicas: 1
  updatedReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  conditions:
    - type: Available
      status: 'True'
      lastUpdateTime: '2023-12-05T05:16:43Z'
      lastTransitionTime: '2023-12-05T05:16:43Z'
      reason: MinimumReplicasAvailable
      message: Deployment has minimum availability.
    - type: Progressing
      status: 'True'
      lastUpdateTime: '2023-12-05T10:15:26Z'
      lastTransitionTime: '2023-12-04T11:34:10Z'
      reason: NewReplicaSetAvailable
      message: ReplicaSet "crm-69596cdf46" has successfully progressed.
